name: Blarg
favicon: null
layout_spectrum: 0.20004986156709492
typography_spectrum: 0.45559603394940495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c3c3c'
    - '#6b6b6b'
    - '#1a1a1a'
    - '#fefefe'
    - '#bcbcbc'
  brandStrength: 1
  lightness: 0.35077978344634175
  saturation: 0.853533674729988
  rhythmicContrast: 0.6676374787930399
purpose: []
